### ISSUE TITLE
required tolid or scientific name even when provided

### ISSUE THREAD

**Issue by ma-diroma** [cnag-aat/ERGA-Status#2]
Hi Tyler,

I'm trying to update the status of one of our species. However the process exits with this message

```
perl update_status.pl -f sequencing_status_update.tsv
Parsed data files... now updating ERGA-Stream.
Updating https://genomes.cnag.cat/erga-stream/api/sequencing/41/
please provide tolid or scientific_name
```

Please find attached my .tsv file (I saved it as a .txt file here on Github)
[sequencing_status_update.tsv.txt](https://github.com/cnag-aat/ERGA-Status/files/14012836/sequencing_status_update.tsv.txt)
In the script the path is set to my perl5 lib and the erga_status_url="https://genomes.cnag.cat/erga-stream/api".

Thanks,
Maria Angela

**Comment by talioto** [comment]
Hmm. I'll use this to debug it. It is trying to update the correct record, so the error message is misleading. Give me a few minutes.

**Comment by talioto** [comment]
Closing the issue.

**Comment by ma-diroma** [comment]
Thank you, Tyler!
