### ISSUE TITLE
status still "waiting" after updating to "Done"

### ISSUE THREAD

**Issue by ma-diroma** [cnag-aat/ERGA-Status#3]
Hi Tyler,

We performed hifi sequencing of a few species and I updated their status using your `update_status.pl` script. However, the status shown in the browser seems not updated.
![Immagine 2024-01-24 114544](https://github.com/cnag-aat/ERGA-Status/assets/13780606/72ed3155-f110-4c07-95a0-2559994a0929)

![immagine](https://github.com/cnag-aat/ERGA-Status/assets/13780606/7aba42a3-38d6-4ce1-ab89-f9ec1729132c)

I expected to see "Done" in the field "Long-read" rather than "Waiting". Could you please tell me if it is how it should work?
In the Log section the process "long_seq" was correctly updated and the status is "Done".

![immagine](https://github.com/cnag-aat/ERGA-Status/assets/13780606/1ceab889-71e4-4a89-adda-0677b61bb0ff)

I also used the `update_runs.pl`. It worked for all my runs, except for a species (Alyssoides utriculata) whose tube ID was not recognized because was not in the form "FS12345678"

`No sample found for Alyssoides utriculata with tube_or_well_id:AU_1-1`

Another issue: I did not obtain the biosample accession as output of run updating and on the erga-stream browser none of my runs is listed in the Runs section.

Could you please help me?
Best,
Maria Angela

**Comment by talioto** [comment]
I've pushed some changes to update_runs.pl and update_status.pl. Can you try again? Tube IDs are still hard to match up if the sample coordinator doesn't submit them correctly to COPO. I am now searching against the GAL_SAMPLE_ID. I will add more identifiers. If it still doesn't match up with a sample, you can manually browse the tracker to see if you can find the correct samples. Pooled samples should be listed as a comma-delimited list and it will try to return a comma-delimited list of BioSample accession numbers.

**Comment by ma-diroma** [comment]
I got this error now when launching both scripts

update_status.pl 
`Can't find string terminator "END_HELP" anywhere before EOF at update_status.pl line 20.`

update_runs.pl
`Can't find string terminator "END_HELP" anywhere before EOF at update_runs.pl line 19.`

I tried to debug but I can't find where the bug is.

**Comment by ma-diroma** [comment]
I got this new error when launching `update_status.pl`

```
Parsed data files... now updating ERGA-Stream.
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE HTML PUBLI...") at update_status.pl line 140.
```

About `update_runs.pl`, it seems it works better, now I see my species in the Runs section on the website. The native file (BAM) md5sum was present in my .tsv file, but is missing on the website. 

I used GAL_SAMPLE_ID for Alyssoides. I still got this error

`No sample found for Alyssoides utriculata with tube_or_well_id or gal_sample_id:FLR0000162`

However, it was recorded on the page, but BioSample Accession is missing for this sample.

**Comment by ma-diroma** [comment]
Update: I re-run `update_runs.pl` for Alyssoides removing tube_or_well_id in the header and adding gal_sample_id. Now it works perfectly, generating a biosample accession. On the website the tube_or_well_id field remains empty and GAL ID is not reported, so there is no identification of the sample

**Comment by ma-diroma** [comment]
I'm sorry to bother you again. I have just checked the Biosample Accession I got using your script for Alyssoides (I have used gal_id rather than tube_or_well_id for this species). The Biosample accession is SAMEA114553221, but I checked here https://genomes.cnag.cat/erga-stream/samples/, it is associated to a different species (Hydrurus foetidus).

**Comment by talioto** [comment]
We just completed migration of the db to a new server and there are some lingering issues, such as being able to sign in, but I'll look into the problem. I thought I saw something like this the other day with an incorrect assignment to H. foetidus

**Comment by talioto** [comment]
I finished restoring the up-to-date database, which includes the runs you uploaded. I see that for teh two runs in question (m54330Ue_231126_031451.hifi_reads.fastq.gz and m54330Ue_231130_123139.hifi_reads.fastq.gz) there is no tube_or_well_id shown, in which case I guess my code is reverting to the first sample in the database (SAMEA114553221). This is poor behavior on my part and I will fix it, but you say you entered the gal_sample_id, instead. This still needs to go in the same column of the tsv (under tube_or_well_id) to be picked up by the script.  Can you post your tsv file here so I can see what's going on?
