### ISSUE TITLE
unable to update status/runs

### ISSUE THREAD

**Issue by ma-diroma** [cnag-aat/ERGA-Status#4]
Hi Tyler,

I am using the latest versions of your scripts update_status.pl and update_runs.pl. I modified the line to point to my perl modules.
The URL specified in the .ergastream.cnf file is  https://genomes.cnag.cat/erga-stream/api. I am logging in using the credentials you gave me.
I am getting these new errors and I am not sure how to solve them. 

```
perl update_status.pl -f sequencing_status_update_032224.tsv
Parsed data files... now updating ERGA-Stream.
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Can't connect to gen...") at update_status.pl line 123.
```

```
perl update_runs.pl -f sequencing_runs_update_032224.tsv
Parsed data files... now updating ERGA-Stream.
Adelopsella bosnica
yield: 22980000000
Can't connect to genomes.cnag.cat:443

SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure at /usr/share/perl5/LWP/Protocol/http.pm line 47.


malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Can't connect to gen...") at update_runs.pl line 185.
```

Please find attached the 2 .tsv file I am using. 
Could you please help me?

Thanks,
Maria Angela
[sequencing_status_update_032224.tsv.txt](https://github.com/cnag-aat/ERGA-Status/files/14722002/sequencing_status_update_032224.tsv.txt)
[sequencing_runs_update_032224.tsv.txt](https://github.com/cnag-aat/ERGA-Status/files/14722003/sequencing_runs_update_032224.tsv.txt)

**Comment by talioto** [comment]
It is a temporary problem with the web server configuration since March 11. There is nothing wrong with the code. I hope it will be fixed soon.

⁣Get BlueMail for Android ​

**Comment by ma-diroma** [comment]
Hi Tyler,

I'm still having these exact issues also with the latest version of your scripts. Could you please help me?

Thanks,
Maria Angela

**Comment by ma-diroma** [comment]
I used your scripts on another server and now they work.

**Comment by talioto** [comment]
I'm so glad. Sorry for the troubles. It IS very possible there are bugs. I continue trying to make it more robust, so please keep raising issues. More documentation and test sets are needed. Hopefully in June I'll find some time to work some more in this part.

Tyler

Get BlueMail for Android<https://bluemail.me>
On May 16, 2024, at 16:30, Maria Angela Diroma ***@***.******@***.***>> wrote:

I used your scripts on another server and now they work.
